# Generated by Django 4.2.13 on 2024-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="production_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
